#!/bin/bash
#
# Setup the keystore and create the RSA keypair for
# signature
#
# $Rev: 4026 $

SCRIPT=$(basename $BASH_SOURCE)
info() { echo >&2 "$SCRIPT: $*"; }
error() { echo >&2 "$SCRIPT: $*"; exit 1; }

# PV-CPS configuration
CONFDIR=$HOME/tmp
KEYSTORE=$CONFDIR/keystore
KEYSTORE_PASSWORD=mustbechanged
KEY=cryptotestkey
KEY_PASSWORD=mustreallybechanged
KEY_SIZE=1024
CERTFILE=$CONFDIR/$KEY-cert
DNAME="O=Tester, L=Paris, C=FR"

# Locate keytool utility
KEYTOOL=
for f in $( (ls /usr/java/default/bin/keytool; ls /usr/java/*/bin/keytool; find /usr/java -name keytool; which keytool) 2>/dev/null); do
    if [[ -x $f ]]; then
        KEYTOOL=$f
        break
    fi
done
[[ -z "$KEYTOOL" ]] && error "keytool utility not found"

# Create keystore and key pair
if [[ -f $KEYSTORE ]]; then
    info "$KEYSTORE already exist, will not overwrite it"
else
    info "generating RSA key pair..."
    $KEYTOOL -genkeypair -alias $KEY -keyalg RSA -keysize $KEY_SIZE -validity 100000 -dname "$DNAME" \
        -keystore $KEYSTORE -storepass $KEYSTORE_PASSWORD -keypass $KEY_PASSWORD
fi
chown pvcps:pvcps $KEYSTORE
chmod 400 $KEYSTORE

# Export public key certificate
$KEYTOOL -exportcert -alias $KEY -file $CERTFILE.pem -rfc \
    -keystore $KEYSTORE -storepass $KEYSTORE_PASSWORD -keypass $KEY_PASSWORD
openssl x509 -in $CERTFILE.pem -out $CERTFILE.txt -text
chown pvcps:pvcps $CERTFILE.pem $CERTFILE.txt
chmod 640 $CERTFILE.pem $CERTFILE.txt
